"""Regenerate mockups/jules-data.js from the original explorer page.

Lifts the four JSON payloads out of The-Adventures-of-Jules.html and writes them as
globals, so the mockups can share one copy of the real data instead of inlining ~471 KB
twice. Reads the page read-only; never writes to it.

    python mockups/tools/extract-data.py

Run from the repo root (or anywhere — paths resolve relative to this file).
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(ROOT, "The-Adventures-of-Jules.html")
OUT = os.path.join(ROOT, "mockups", "jules-data.js")

BLOBS = [("sndata", "SN"), ("inteldata", "IE"), ("gossipdata", "GOSSIP"), ("interactions", "INTER")]

# The counts in the real save. If these ever fail, the page changed and the mockups'
# README (which quotes them) is stale too.
EXPECT = {"memories": 255, "screenshots": 163, "GOSSIP": 54, "INTER": 62}


def main():
    if not os.path.exists(SRC):
        sys.exit("FATAL: cannot find %s" % SRC)
    html = io.open(SRC, encoding="utf-8").read()

    parsed = {}
    for blob_id, var in BLOBS:
        m = re.search(r'<script type="application/json" id="%s">(.*?)</script>' % blob_id, html, re.S)
        if not m:
            sys.exit("FATAL: payload '%s' not found in the page" % blob_id)
        parsed[var] = json.loads(m.group(1))

    assert len(parsed["SN"]["memories"]) == EXPECT["memories"], len(parsed["SN"]["memories"])
    assert len(parsed["SN"]["screenshots"]) == EXPECT["screenshots"], len(parsed["SN"]["screenshots"])
    assert len(parsed["GOSSIP"]) == EXPECT["GOSSIP"], len(parsed["GOSSIP"])
    assert len(parsed["INTER"]) == EXPECT["INTER"], len(parsed["INTER"])

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by mockups/tools/extract-data.py — do not hand-edit.\n")
        f.write("// The four payloads The-Adventures-of-Jules.html embeds as\n")
        f.write("// <script type=\"application/json\">, re-exported as globals.\n")
        for _, var in BLOBS:
            # ensure_ascii keeps the file ASCII-safe; </ escaped so no record text can
            # close a <script> block when this is loaded.
            s = json.dumps(parsed[var], ensure_ascii=True, separators=(",", ":")).replace("</", "<\\/")
            f.write("window.%s = %s;\n" % (var, s))

    print("wrote %s (%.0f KB)" % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT) / 1024.0))
    for _, var in BLOBS:
        v = parsed[var]
        print("  %-6s %s" % (var, len(v) if isinstance(v, list) else "%d keys" % len(v)))


if __name__ == "__main__":
    main()
