"""Regenerate mockups/fixtures/*.js — synthetic edge cases for testing the mockups.

Jules is a rich save: 14 days, a war, a diary, gossip, 163 captures, and only 7 undated
memories. It hides every empty-state and bad-data bug. These fixtures don't.

    minimal.js   a thin save — 2 days, no captures, no diary, no war, no gossip
    nulldays.js  the quarantine path — most memories undated with wall-clock in `gt`,
                 plus captures that match no day on the calendar

Both are derived by subsetting/mutating the real payload, so field shapes cannot drift
from the real schema. Load one with ?data=minimal / ?data=nulldays on either mockup.

    python mockups/tools/make-fixtures.py
"""
import copy
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(ROOT, "The-Adventures-of-Jules.html")
OUTDIR = os.path.join(ROOT, "mockups", "fixtures")


def blob(html, blob_id):
    m = re.search(r'<script type="application/json" id="%s">(.*?)</script>' % blob_id, html, re.S)
    if not m:
        sys.exit("FATAL: payload '%s' not found" % blob_id)
    return json.loads(m.group(1))


def write(name, sn, ie, gossip, inter, note):
    os.makedirs(OUTDIR, exist_ok=True)
    path = os.path.join(OUTDIR, name + ".js")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by mockups/tools/make-fixtures.py — do not hand-edit.\n// %s\n" % note)
        for var, val in (("SN", sn), ("IE", ie), ("GOSSIP", gossip), ("INTER", inter)):
            s = json.dumps(val, ensure_ascii=True, separators=(",", ":")).replace("</", "<\\/")
            f.write("window.%s = %s;\n" % (var, s))
    print("  %-12s %6.1f KB  %s" % (name + ".js", os.path.getsize(path) / 1024.0, note))


def build_minimal(SN, IE):
    """A save with almost nothing in it. Every conditional view must vanish cleanly."""
    days2 = SN["ordered_days"][:2]
    mem2 = [m for m in SN["memories"] if m.get("day") in days2][:13]

    # Rebuild edges against the reduced list; drop any edge pointing outside it, or the
    # constellation would index past the end of the array.
    old_to_new = {}
    for i, m in enumerate(SN["memories"]):
        for j, m2 in enumerate(mem2):
            if m is m2:
                old_to_new[i] = j
    edges2 = [[old_to_new[a], old_to_new[b], s] for a, b, s in SN["edges"]
              if a in old_to_new and b in old_to_new]

    counts = {}
    for m in mem2:
        counts[m["actor"]] = counts.get(m["actor"], 0) + 1
    actors2 = [{"name": k, "count": v} for k, v in sorted(counts.items(), key=lambda x: -x[1])]

    sn = {
        "player": "Brynja",
        "stats": {"events": 118, "memories": len(mem2), "minds": len(actors2), "captures": 0,
                  "days": 2, "kills": 3,
                  "subtitle": "Brynja — 19th to 20th of Last Seed, 4E 201 · ~2.4 hours played",
                  "play_hours": 2.4},
        "ordered_days": days2,
        "events_by_day": {k: v for k, v in SN["events_by_day"].items() if k.split("|")[0] in days2},
        "actors": actors2,
        "memories": copy.deepcopy(mem2),
        "edges": edges2,
        "pca_var": SN["pca_var"],
        "proj_method": SN["proj_method"],
        "leaderboard": [{"killer": "Brynja", "total": 3, "cats": {"Wildlife": 2, "People": 1},
                         "victims": [["Wolf", 2], ["Bandit", 1]]}],
        "diary": [],          # no diary   -> view omitted
        "screenshots": [],    # no captures -> view omitted
        "omni_summary": {},
        "feature": {},        # nothing notable -> view omitted
    }
    ie = {
        "factions": IE["factions"][:3],
        "relations": IE["relations"][:2],
        "events": IE["events"][:4],
        "player_standing": [],
        "has_war": False,     # no war -> war + battles views omitted
        "war": [],
        "battles": [],
    }
    return sn, ie, len(mem2), len(days2)


def build_nulldays(SN):
    """The quarantine path: wall-clock leaked into `gt`, and captures that match no day.

    Mirrors the real bug — in the actual save, 6 memories carry a Unix epoch in `gt` and
    are exactly the ones with no resolvable day. Here it's forced onto 60% of rows.
    """
    sn = copy.deepcopy(SN)
    EPOCH = 1784014205.3  # decodes to 2026-07-14 — a real-world timestamp, not game time
    for i, m in enumerate(sn["memories"]):
        if i % 10 >= 4:
            m["day"] = None
            m["gt"] = EPOCH + i * 0.03
    sn["stats"] = dict(sn["stats"])
    sn["stats"]["subtitle"] = "Jules — a save where most memories lost their timestamp"

    # A capture on a day with no events, so it isn't on `ordered_days` at all. Jules cannot
    # produce this case: it has events every single day.
    orphan = copy.deepcopy(sn["screenshots"][0])
    orphan["ts"] = "3:15 PM, Fredas, 2nd of Hearthfire, 4E 201"
    orphan["name"] = "OrphanedCapture"
    # A capture whose ts isn't the format payloads.md never actually pinned down.
    weird = copy.deepcopy(sn["screenshots"][1])
    weird["ts"] = "1428.55"
    weird["name"] = "UnparseableTimestamp"
    sn["screenshots"] = sn["screenshots"][:24] + [orphan, weird]
    return sn, sum(1 for m in sn["memories"] if m["day"] is None)


def main():
    if not os.path.exists(SRC):
        sys.exit("FATAL: cannot find %s" % SRC)
    html = io.open(SRC, encoding="utf-8").read()
    SN, IE = blob(html, "sndata"), blob(html, "inteldata")
    GOSSIP, INTER = blob(html, "gossipdata"), blob(html, "interactions")

    sn_min, ie_min, nmem, ndays = build_minimal(SN, IE)
    write("minimal", sn_min, ie_min, [], [],
          "2 days, no captures, no diary, no war, no gossip, no feature")

    sn_null, n_null = build_nulldays(SN)
    write("nulldays", sn_null, IE, GOSSIP, INTER,
          "%d/%d memories undated w/ epoch-contaminated gt; 2 captures unmatchable to a day"
          % (n_null, len(sn_null["memories"])))

    print("\nminimal:  %d memories over %d days" % (nmem, ndays))
    print("nulldays: %d/%d memories undated" % (n_null, len(sn_null["memories"])))


if __name__ == "__main__":
    main()
